[package]
name = "torus"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.2"
image = "0.24.6"
rayon = "1.5.1"
winit = "0.28.3"
pixels = "0.12.1"
bracket-noise = "0.8.7"
noise = "0.8.2"
rand = "0.8.5"
wgpu = "0.16.0"
num_cpus = "1.15.0"
